### ISSUE TITLE
新小米路由器更新了加密方法 sha256

### ISSUE THREAD

**Issue by 885783558** [HuckOps/miwifi_exporter#10]
获取路由器登录页错误，可能原因：1.配置的路由器IP错误 Get "http://192.168.31.1/cgi-bin/luci/web/home": dial tcp 192.168.31.1:80: connect: connection refused

**Comment by 885783558** [comment]
<img width="1015" alt="image" src="https://github.com/HuckOps/miwifi_exporter/assets/15685121/c1f543c7-6302-486e-b0a2-c363fee0f3d2">
密码没问题啊

**Comment by 885783558** [comment]
参考 https://www.52pojie.cn/thread-1832133-1-1.html 改成 sha256 就可以了

**Comment by HuckOps** [comment]
看来是新路由器或者新固件才是这样？我这老机器好像还正常
