### ISSUE TITLE
这个可以用在红米6000上吗,我的出现下面的错误

### ISSUE THREAD

**Issue by w55554** [HuckOps/miwifi_exporter#6]
2024/03/19 10:19:44 欢迎使用小米路由器监控prometheus客户端，项目名miwifi_exporter，作者：Huck，欢迎提交issues、PullRequest
2024/03/19 10:19:44 初始化程序
2024/03/19 10:19:44 从 config.json 读取配置
2024/03/19 10:19:44 获取到的地址:  192.168.50.1 密码:  xxxx 端口:  9001
2024/03/19 10:19:44 开始获取Token
2024/03/19 10:20:14 获取路由器登录页错误，可能原因：1.配置的路由器IP错误 Get "http://192.168.50.1/cgi-bin/luci/web/home": dial tcp 192.168.50.1:80: i/o timeout

**Comment by HuckOps** [comment]
看起来像端口或者ip不通，要不就是后台有问题，建议检查一下路由器

**Comment by HuckOps** [comment]
找到原因，小米路由器新固件使用了密码加密传输，我手头没有设备没法测
